name: msms_rt_score_integration
channels:
  - conda-forge
dependencies:
  - conda-forge::python>=3.8
  - conda-forge::numpy
  - conda-forge::scipy
  - conda-forge::scikit-learn
  - conda-forge::joblib
  - conda-forge::pandas
  - conda-forge::matplotlib
  - conda-forge::seaborn
  - conda-forge::networkx>=2.4
  - conda-forge::rdkit==2021.03.1
