name: Unit-testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9' ]

    defaults:
      run:
        # Set up the default shell. This is needed for the Conda
        shell: bash -l {0}

    steps:
      # ------------------------------------------------------------------------
      # Checkout the branch from the github repository that triggered the action
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      # ------------------------------------------------------------------------

      # --------------------------------------------------
      # Setting up Python using a Conda environment
      - name: Set up Conda with Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: msms_rt_scorer
          environment-file: environment.yml
          channel-priority: strict
      # --------------------------------------------------

      # ------------------------
      # Install the SSVM package
      - name: Install the MSMS RT SCORER package
        run: pip install .
      # ------------------------

      # --------------------------------
      # Check the package version number
      - name: Package version number
        run: python -c "from msmsrt_scorer import __version__; print('msmsrt_scorer-Package version:', __version__)"
      # --------------------------------

      # -----------------
      # Run the unittests
      - name: Run all unittests
        run: |
          cd msmsrt_scorer/lib/tests
          python -m unittest -v Unittests_evaluation_tools.py
          python -m unittest -v Unittests_exact_solvers.py
      # -----------------
